dataloader_kwargs:
  testset:
    batch_size: 64
    drop_last: false
    num_workers: 0
    shuffle: false
  trainset:
    batch_size: 64
    drop_last: false
    num_workers: 0
    shuffle: true
dataset: Cifar10
dataset_kwargs:
  mean:
  - 0.49139968
  - 0.48215827
  - 0.44653124
  portion:
  - 0.1
  - 0.9
  std:
  - 0.24703233
  - 0.24348505
  - 0.26158768
  whether_valid: true
device: cuda
early_stop: true
epochs: 1
eval_no_grad: true
gpus: '0'
grad_clip: 5.0
model: Cifar10_resnet18
model_kwargs: null
objective: ClassificationObjective
objective_kwargs: null
optimizer_kwargs:
  lr: 0.001
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0003
optimizer_type: SGD
path: try
report_every: 0.2
save_as_state_dict: false
save_every: 1
scheduler: MultiStepLR
scheduler_kwargs:
  gamma: 0.1
  milestones:
  - 10
  - 40
  - 100
test_every: 1
trainer_type: FinalTrainer
valid_every: 1
