# An Example Configuration for Training A ResNet18 Model on Cifar10

# ---- Objective ----
objective_type: ClassificationObjective  # Type of objective to use
objective_kwargs:
  criterion_type: LSCrossEntropy         # Type of criterion to use
  criterion_kwargs:
    smooth: 0.2 

# ---- Model ----
model_type: CifarResNet   # Model to train or test
model_kwargs:
  block: BasicBlock
  num_blocks: [2, 2, 2, 2, 2]
  num_classes: 10

# ---- Dataset ----
dataset_type: Cifar10  # Dataset to load
dataset_kwargs:
  path: ~/dltorch_plugins/data/CIFAR10  # Path
  train_transforms: {  # Trainset transforms
    "RandomCrop": {"size": 32, "padding": 4},
    "RandomHorizontalFlip": {},
    "ToTensor": {},
    "Normalize": {
      "mean": [0.49139968, 0.48215827, 0.44653124],
      "std": [0.24703233, 0.24348505, 0.26158768]
      }
    }
  test_transforms: {  # Testset transforms
    "ToTensor": {},
    "Normalize": {
      "mean": [0.49139968, 0.48215827, 0.44653124],
      "std": [0.24703233, 0.24348505, 0.26158768]
      }
    }
    
# ---- Trainer ----
trainer_type: CNNTrainer  # Trainer type
trainer_kwargs:  # Trainer kwargs
  # Dataloader kwargs
  dataloader_kwargs:
    batch_size: 128
    num_workers: 2
    shuffle: true
    drop_last: false
  # Optimizer
  optimizer_type: SGD  # Optimizer type
  optimizer_kwargs:  # Optimizer kwargs
    lr: 0.05
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0003
  # Lr scheduler
  lr_scheduler_type: CosineAnnealingLR  # Lr scheduler type
  lr_scheduler_kwargs:  # Lr scheduler kwargs
    T_max: 100
    eta_min: 0.0001
  # Other cfgs
  epochs: 100
  save_as_state_dict: true
  test_every: 1
  grad_clip: 5.0
  eval_no_grad: true
  early_stop: false
  trainset_portion: [0.8, 0.2]
