# Example Config for FinalTrainer

# ---- Basic Settings ----
trainer_type: CNNFinalTrainer
device: cuda
gpus: 0
epochs: 100
grad_clip: 5.0
eval_no_grad: Trie
early_stop: False
save_as_state_dict: False
path: test
test_every: 1
valid_every: 1
save_every: 50
report_every: 0.5

# ---- Config for model
model: MNIST_LeNet
model_kwargs: NULL

# ---- Config for dataset and dataloader ----
dataset: MNIST
dataset_kwargs:
  dir: E:/DLtorch/DLtorch/datasets/data/MNIST
  whether_valid: False
dataloader_kwargs:
  trainset:
    batch_size: 128
    num_workers: 0
    shuffle: True
    drop_last: False
  testset:
    batch_size: 96
    num_workers: 0
    shuffle: False
    drop_last: False

# ---- Config for objective ----
objective: ClassificationObjective
objective_kwargs:
  criterion_type: CrossEntropyLoss
# ---- Config for optimizer ----
optimizer_type: SGD
optimizer_kwargs:
  lr: 0.001
  momentum: 0.9
  nesterov: True
  weight_decay: 0.0001

# ---- Config for scheduler ----
scheduler: CosineAnnealingLR
scheduler_kwargs:
  T_max: 100
  eta_min: 0.0
