# Example Config for register new components.

# DLtorch Framework
# Author: Junbo Zhao <zhaojb17@mails.tsinghua.edu.cn>.

# An Example Configuration for Adversarial Training Cifar10.

# ---- Basic Settings ----
trainer_type: CNNFinalTrainer      # Type of trainer to use.
device: cuda                       # Device to use. ["cpu","cuda"]
gpus: 0                            # Gpus to use. If a list, for example, "[0, 1]" is given, computation will automatically be paralleled.
epochs: 100                        # Total epoch number to train.
grad_clip: 5.0                     # Grad clip. Won't do clip if it's not given.
eval_no_grad: False                # Whether to close grad while inference. Grad needed for adversarial attack.
early_stop: False                  # Whether use early stop. Remember to set "whether_valid" to be true, if use.
save_as_state_dict: False          # Saving file layout.
path: test                         # Path to save. Will be automatically modified if use "DLtorch test" command.
test_every: 1                      # Number of training epochs to test on testset once.
save_every: 50                     # Number of training epochs to save once.
report_every: 0.5                  # Reporting frequency.

# ---- Config for model ----
model: Cifar_resnet18              # Model to train or test.
model_kwargs: NULL                 # Model kwargs.

# ---- Config for dataset and dataloader ----
dataset: Cifar10                   # Dataset to load.
dataset_kwargs:
  dir: E:/DLtorch/DLtorch/datasets/data/cifar10 # Path
  whether_valid: False                        # If true, the training set will be devided according to portion.
dataloader_kwargs:                            # Dataloader kwargs.
  trainset:
    batch_size: 16
    num_workers: 0
    shuffle: True
    drop_last: False
  testset:
    batch_size: 16
    num_workers: 0
    shuffle: False
    drop_last: False

# ---- Config for objective ----
objective: ExampleNewObjective
objective_kwargs:
  criterion_type: CrossEntropyLoss # Objective type.
  criterion_kwargs: NULL

# ---- Config for optimizer ----
optimizer_type: SGD                           # Optimizer type.
optimizer_kwargs:                             # Optimizer kwargs.
  lr: 0.1
  momentum: 0.9
  nesterov: True
  weight_decay: 0.0001

# ---- Config for scheduler ----
scheduler: CosineAnnealingLR                  # Scheduler type.
scheduler_kwargs:                             # Scheduler kwargs.
  T_max: 100
  eta_min: 0.0