# Example Config for FinalTrainer

# ---- Basic Settings ----
trainer_type: CNNFinalTrainer
device: cuda
gpus: 0
epochs: 100
grad_clip: 5.0
eval_no_grad: False
early_stop: True
save_as_state_dict: False
path: test
test_every: 1
valid_every: 1
save_every: 20
report_every: 0.2

# ---- Config for model
model: Cifar10_resnet18
model_kwargs: NULL

# ---- Config for dataset and dataloader ----
dataset: Cifar10
dataset_kwargs:
  dir: E:/datasets/CIFAR10
  mean:
    - 0
    - 0
    - 0
  std:
    - 1
    - 1
    - 1
  whether_valid: True
  portion:
    - 0.90
    - 0.10
dataloader_kwargs:
  trainset:
    batch_size: 16
    num_workers: 0
    shuffle: True
    drop_last: False
  testset:
    batch_size: 16
    num_workers: 0
    shuffle: False
    drop_last: False

# ---- Config for objective ----
objective: ClassificationAdversarialObjective
objective_kwargs:
  adversary_type: FGSM
  adversary_kwargs:
    rand_init: True
    criterion_type: CrossEntropyLoss
    epsilon: 0.031
  adv_loss_coef: 0.5
  adv_reward_coef: 0.5
  criterion_type: CrossEntropyLoss
# ---- Config for optimizer ----
optimizer_type: SGD
optimizer_kwargs:
  lr: 0.001
  momentum: 0.9
  nesterov: True
  weight_decay: 0.0003

# ---- Config for scheduler ----
scheduler: MultiStepLR
scheduler_kwargs:
  milestones:
    - 10
    - 40
    - 100
  gamma: 0.1